export const HOME_GET_INITIAL_STATE_BEGIN = 'HOME_GET_INITIAL_STATE_BEGIN';
export const HOME_GET_INITIAL_STATE_SUCCESS = 'HOME_GET_INITIAL_STATE_SUCCESS';
export const HOME_GET_INITIAL_STATE_FAILURE = 'HOME_GET_INITIAL_STATE_FAILURE';
export const HOME_GET_INITIAL_STATE_DISMISS_ERROR = 'HOME_GET_INITIAL_STATE_DISMISS_ERROR';
export const HOME_GET_MAIN_STATE_BEGIN = 'HOME_GET_MAIN_STATE_BEGIN';
export const HOME_GET_MAIN_STATE_SUCCESS = 'HOME_GET_MAIN_STATE_SUCCESS';
export const HOME_GET_MAIN_STATE_FAILURE = 'HOME_GET_MAIN_STATE_FAILURE';
export const HOME_GET_MAIN_STATE_DISMISS_ERROR = 'HOME_GET_MAIN_STATE_DISMISS_ERROR';
